name: CI/CD Pipeline for Node.js with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build and test application
        run: |
          npm run build
          npm test

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
       if [ ! -d "/home/***/newnodejs/.git" ]; then
            rm -rf /home/***/newnodejs
            git clone https://github.com/JafferRaza123/nodejs.git /home/***/newnodejs
          fi
          cd /home/***/newnodejs
          git pull origin main
          docker-compose down -v
          docker-compose up -d --force-recreate
